# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4dc5251f8c1a82caf21293dab03ee63ac90e9422d2b9dc82ff1993bc18a554bfa6b8296184808f2683cbb6365b2e27198668aa922456d8ed08d3ba3abc9dc2d0

test:
  secret_key_base: 0759388bc85bcbc63fda61134de412f7899556e538f447501a0941bcbb0cb1b8790cd87f6c21aad8860a582289e7b62dd6d74b389998696383b5e8903f3cea94

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
